services:
  db:
    image: arangodb:3.12.9
    container_name: db
    environment:
      - ARANGO_ROOT_PASSWORD=${ARANGO_ROOT_PASSWORD}
    ports:
      - "127.0.0.1:8529:8529" # Для тестирования
    volumes:
      - arangodb_data:/var/lib/arangodb3
    networks:
      - backend_network
    restart: unless-stopped
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - .env
    networks:
      - backend_network
    depends_on:
      - db
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: dev
    container_name: client
    ports:
      - "127.0.0.1:5173:5173"
    env_file:
      - .env
    volumes:
      - ./client:/app
      - client_node_modules:/app/node_modules
    networks:
      - backend_network
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  arangodb_data:
  client_node_modules:

networks:
  backend_network:
    driver: bridge
